#!/bin/bash

sudo rm -rf /usr/local/bin/*opencv*
sudo rm -rf /usr/local/include/opencv*
sudo rm -rf /usr/local/lib/*opencv*
sudo rm -rf /usr/local/share/opencv*
sudo rm -rf /usr/local/lib/pkgconfig/opencv*
sudo rm -rf /usr/local/lib/python3.*/dist-packages/cv2
sudo rm -rf /usr/local/lib/python3.*/site-packages/cv2
