#!/bin/bash

echo '---------------Uninstall CUDA and NvidiaDriver'

sudo apt-get --purge remove "*cublas*" "cuda*" "nsight*" 
sudo apt-get --purge remove "*nvidia*"
sudo rm -rf /usr/local/cuda*
echo '--------------- Restart'

echo '--------------- Done'
